# Generated by Django 5.2.8 on 2025-11-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('nft_token_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('blockchain_minted', models.BooleanField(default=False)),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
