# Generated by Django 5.2.8 on 2025-12-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('blockchain', 'Blockchain'), ('business', 'Business'), ('ai', 'AI & Machine Learning'), ('data', 'Data Science'), ('other', 'Other')], max_length=50),
        ),
    ]
